- name: Restart service
  service:
    name: "{{ service_name }}"
    state: restarted
  when: service_name is defined

- name: Reload configuration
  command: "{{ config_reload_command }}"
  when: config_reload_command is defined