# This file contains the inventory of hosts for the development environment.

all:
  hosts:
    dev-server-1:
      ansible_host: 192.168.1.10
      ansible_user: devuser
      ansible_ssh_private_key_file: ~/.ssh/dev_key
      environment: development
    dev-server-2:
      ansible_host: 192.168.1.11
      ansible_user: devuser
      ansible_ssh_private_key_file: ~/.ssh/dev_key
      environment: development

  children:
    web:
      hosts:
        dev-server-1:
        dev-server-2:
      vars:
        http_port: 80
        max_clients: 200

    db:
      hosts:
        dev-server-1:
      vars:
        db_port: 5432
        db_user: devuser
        db_password: devpassword