- name: "Test NetBox interface module"
  connection: local
  hosts: localhost
  gather_facts: False
  vars:
    NETBOX_ENDPOINT: "{{ lookup('env','NETBOX_URL') }}"
    NETBOX_TOKEN: "{{ lookup('env','NETBOX_TOKEN') }}"
    tenant_name: "UM Southwest Key Program"
    site_name: "Program 980 Norma Linda"
    # device: "Admin 1"
    interface: "Management"
    type: "1000Base-t (1GE)"
    # primary_address: "10.100.10.25/32"
  vars_files:
    - "/home/adminswk/cnl/netbox/playbooks/vars.yml"

  tasks:
    - name: Debug NetBox Endpoint and Token
      debug:
        var:
          NETBOX_ENDPOINT: "{{ lookup('env','NETBOX_URL') }}"
          NETBOX_TOKEN: "{{ lookup('env','NETBOX_TOKEN') }}"

    # - name: Create Devices
    #   netbox.netbox.netbox_device:
    #     netbox_url: "{{ NETBOX_ENDPOINT }}"
    #     netbox_token: "{{ NETBOX_TOKEN }}"
    #     validate_certs: false
    #     data:
    #       name: "{{ item.device }}"
    #       site: "{{ site_name }}"
    #       tenant: "{{ tenant_name }}"
    #       device_type: "{{ item.device_type }}"
    #       device_role: switch
    #       platform: edgeswitch
    #   loop: "{{ devices }}"

    - name: Create Management Interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ NETBOX_ENDPOINT }}"
        netbox_token: "{{ NETBOX_TOKEN }}"
        validate_certs: false
        data:
          device: "{{ item.device }}"
          name: "{{ interface }}"
          type: "{{ type }}"
          mgmt_only: true
        state: present
      loop: "{{ devices }}"

    - name: Add Primary IP to Management Interface
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ NETBOX_ENDPOINT }}"
        netbox_token: "{{ NETBOX_TOKEN }}"
        validate_certs: false
        data:
          address: "{{item.primary_ip}}"
          assigned_object:
            device: "{{ item.device }}"
            name: "{{ interface }}"
      loop: "{{ devices }}"

    - name: Update Management Interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ NETBOX_ENDPOINT }}"
        netbox_token: "{{ NETBOX_TOKEN }}"
        validate_certs: false
        data:
          device: "{{ item.device }}"
          name: "{{ interface }}"
          mgmt_only: true
      loop: "{{ devices }}"

    - name: Update Primary IP
      netbox.netbox.netbox_device:
        netbox_url: "{{ NETBOX_ENDPOINT }}"
        netbox_token: "{{ NETBOX_TOKEN }}"
        validate_certs: false
        data:
          name: "{{ item.device }}"
          site: "{{ site_name }}"
          tenant: "{{ tenant_name }}"
          primary_ip4: "{{ item.primary_ip }}"
      loop: "{{ devices }}"