- hosts:
    - name: production-server-1
      ansible_host: 192.168.1.10
      ansible_user: deploy
      ansible_ssh_private_key_file: /path/to/private/key
      vars:
        http_port: 80
        max_clients: 200

    - name: production-server-2
      ansible_host: 192.168.1.11
      ansible_user: deploy
      ansible_ssh_private_key_file: /path/to/private/key
      vars:
        http_port: 80
        max_clients: 200

    - name: production-database
      ansible_host: 192.168.1.12
      ansible_user: dbuser
      ansible_ssh_private_key_file: /path/to/private/key
      vars:
        db_name: production_db
        db_user: dbuser
        db_password: securepassword