---
# tasks file for save_config
- name: Save configuration
  ansible.netcommon.cli_command:
    command: show run
  register: cmd_output

- name: Set fact for use outside the role
  set_fact:
    show_run_data: "{{ cmd_output.stdout }}"