---
- name: Debug interfaces from NetBox using URI calls
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    NETBOX_URL: "{{ lookup('env','NETBOX_URL') }}"
    NETBOX_TOKEN: "{{ lookup('env','NETBOX_TOKEN') }}"

  tasks:
    - name: 1 - Get Devices
      uri:
          url: "{{ NETBOX_URL }}api/dcim/devices/?name={{ inventory_hostname }}"
          method: GET
          return_content: yes
          validate_certs: no          
          headers:
              accept: "application/json"
              Authorization: "Token {{ NETBOX_TOKEN }}"
      register: device

    - name: 2 - Get Interfaces
      uri:
          url: "{{ NETBOX_URL }}api/dcim/interfaces/?device={{ inventory_hostname }}&limit=0"
          method: GET
          return_content: yes
          validate_certs: no 
          headers:
              accept: "application/json"
              Authorization: "Token {{ NETBOX_TOKEN }}"
      register: interfaces

    - name: Show interface list
      debug:
        msg: "{{ interfaces.json.results | json_query('[].{name: name, mode: mode, untagged: untagged_vlan.vid, tagged: tagged_vlans[*].vid}') }}"
