---
- name: Debug interfaces from NetBox using nb_lookup
  hosts: all
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('env', 'netbox_url') }}"
    netbox_token: "{{ lookup('env', 'netbox_token') }}"

  tasks:
    - name: Lookup interfaces from NetBox
      set_fact:
        netbox_interfaces: >-
          {{ query('netbox.netbox.nb_lookup', 'interfaces',
                   api_endpoint=netbox_url,
                   token=netbox_token,
                   validate_certs=False,
                   api_filter=device_id={{ hostvars[inventory_hostname].id }}) }}

    - name: Show interface list
      debug:
        msg: "{{ netbox_interfaces | json_query('[].{name: name, mode: mode, untagged: untagged_vlan.vid, tagged: tagged_vlans[*].vid}') }}"
