---
- name: Example Ansible Playbook with VLAN for Dell OS6
  hosts: all
  gather_facts: no
  collections:
    - dellemc.os6

  vars:
    os6_vlan:
      vlan 10:
        name: "Users"
        state: present
      vlan 20:
        name: "Voice"
      state: present
    ansible_network_os: dellemc.os6.os6
    ansible_become: yes
    ansible_become_method: enable
  roles:
    - os6_vlan