---
- name: Gather facts from Dell EMC OS6 device
  hosts: all
  gather_facts: no

  tasks:
    - name: Collect facts
      os6_facts:
        gather_subset: all
      register: os6_facts

    - name: Show gathered facts
      debug:
        var: os6_facts
