---
- name: Pull interface info from NetBox
  hosts: localhost
  gather_facts: no
  collections:
    - netbox.netbox

  vars:
    netbox_url: "{{ lookup('env','NETBOX_URL') }}"
    netbox_token: "{{ lookup('env','NETBOX_TOKEN') }}"
    device_name: "{{ inventory_hostname }}"  # Replace with the actual device name

  tasks:
    #Print inventory_hostname
    - name: Print inventory_hostname
      debug:
        msg: "The inventory_hostname is {{ inventory_hostname }}"

    - name: Get device data from NetBox
      set_fact:
        device_data: "{{ lookup('netbox.netbox.nb_lookup', 'devices', api_filter='name=' + device_name, api_endpoint=netbox_url, token=netbox_token, validate_certs=False) }}"

    - name: Get interfaces from device
      set_fact:
        interfaces: "{{ lookup('netbox.netbox.nb_lookup', 'interfaces', api_filter='device_id=' + (device_data.value.id | string) , api_endpoint=netbox_url, token=netbox_token, validate_certs=False) }}"

    - name: Print interface information
      debug:
        var: interfaces
