---
- name: Configurar switches por sitio
  hosts: all
  gather_facts: no
  collections:
    - dellemc.os6  
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: dellemc.os6.os6
    hostname: "{{ inventory_hostname }}"

  tasks:
    - name: Aplicar hostname con rol oficial OS6
      import_role:
        name: dellemc.os6.hostname