- name: Cambiar hostname con os6_config
  hosts: os6_switches
  gather_facts: no
  connection: network_cli
  collections:
    - dellemc.os6
  tasks:
    - name: Cambiar hostname a SW-LAB01
      os6_config:
        lines:
          - hostname SW-LAB01
