---
- name: Configurar switches por sitio
  hosts: all
  gather_facts: no
  collections:
    - dellemc.os6  
  
  tasks:
    - name: Cambiar hostname a SW-LAB01
      os6_config:
        lines:
          - hostname SW-LAB01
