---
- name: Test os6_command module
  hosts: all
  gather_facts: no
  collections:
    - dellemc.os6
  vars:
    ansible_connection: network_cli
    ansible_network_os: dellemc.os6.os6
    ansible_become: yes
    ansible_become_method: enable
  tasks:
    - name: Set hostname using os6_command
      os6_command:
        commands:
          - "configure terminal"
          - "hostname Test-Switch"
          - "exit"