---

- name: Gather facts from EdgeSwitch
  hosts: bck
  gather_facts: no
  become: true
  become_method: enable
   
  tasks:
    - name: Get switch facts
      community.network.edgeswitch_facts:
        gather_subset: config
      register: switch_facts

    - name: switch_facts stdout_lines
      debug:
        var: switch_facts
