---

- name: Gather facts from EdgeOS switches
  hosts: backup
  gather_facts: no
  become: true
  become_method: enable
  
  tasks:
    - name: Set trunk port uplinks Edgeswitch
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop:
        - "configure"
        - "interface {{ vlan_configurations[0].uplink_trunk_ports }}"
        - "description 'Uplink to bridge switch'"
        - "switchport mode trunk"
        - "exit"
        - "exit"

    
    - name: Set trunk port downlink to the south network
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop:
        - "configure"
        - "interface {{ vlan_configurations[0].downlink_trunk_ports }}"
        - "description 'trunk downlink to south network'"
        - "switchport mode trunk"
        - "spanning-tree guard root"
        - "exit"
        - "exit"
    
      
  