---
# tasks file for reset_trunk_config

- name: Reset trunk ports to default configuration to downlink
  ansible.netcommon.cli_command:
    command: "{{ item }}"
  loop:
    - "configure"
    - "interface {{ vlan_configurations[0].downlink_trunk_ports }}"
    - "no description"
    - "switchport mode general"
    - "no spanning-tree guard root"
    - "exit"
    - "exit"
  when: vlan_configurations[0].downlink_trunk_ports != '0/0'



- name: Reset trunk ports to default configuration to uplinks
  ansible.netcommon.cli_command:
    command: "{{ item }}"
  loop:
    - "configure"
    - "interface {{ vlan_configurations[0].uplink_trunk_ports }}"
    - "no description"
    - "switchport mode general"
    - "exit"
    - "exit"
  when: vlan_configurations[0].uplink_trunk_ports != '0/0'
