version: "3.4"

services:
  netbox:
    image: netboxcommunity/netbox:v4.2-3.2.0
    ports:
      - 8000:8080
    environment:
      DB_NAME: netbox
      DB_USER: netbox
      DB_HOST: postgres
      DB_PASSWORD: J5brHrAXFLQSif0K
      REDIS_PASSWORD: redis123
      REDIS_CACHE_PASSWORD: redis456
      REDIS_HOST: redis
      REDIS_CACHE_HOST: redis-cache
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_PASSWORD: admin123
      SECRET_KEY: "^U+NyW0(Omty^CEo6q$3DY0RxHaBm@_J*83zEHz(6S_vxGTXOY"
      DB_WAIT_TIMEOUT: 60
      DB_WAIT_DEBUG: 1
    command:
      - sh
      - -c
      - |
        uv pip install netbox-topology-views && /opt/netbox/docker-entrypoint.sh /opt/netbox/launch-netbox.sh
    depends_on:
      - postgres
      - redis
      - redis-cache
    healthcheck:
      test: curl -f http://localhost:8080/login/ || exit 1
      interval: 15s
      timeout: 3s
      retries: 5
    volumes:
      - netbox-media-files:/opt/netbox/netbox/media
      - netbox-reports-files:/opt/netbox/netbox/reports
      - netbox-scripts-files:/opt/netbox/netbox/scripts
      - netbox_plugins_config:/etc/netbox/config

  netbox-worker:
    image: netboxcommunity/netbox:v4.2-3.2.0
    environment:
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: J5brHrAXFLQSif0K
      REDIS_PASSWORD: redis123
      REDIS_CACHE_PASSWORD: redis456
      SECRET_KEY: "^U+NyW0(Omty^CEo6q$3DY0RxHaBm@_J*83zEHz(6S_vxGTXOY"
      DB_HOST: postgres

      REDIS_HOST: redis
      REDIS_CACHE_HOST: redis-cache
    command:
      - sh
      - -c
      - |
        uv pip install netbox-topology-views && /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py rqworker
    volumes:
      - netbox_plugins_config:/etc/netbox/config
    depends_on:
      - netbox

  netbox-housekeeping:
    image: netboxcommunity/netbox:v4.2-3.2.0
    environment:
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: J5brHrAXFLQSif0K
      REDIS_PASSWORD: redis123
      REDIS_CACHE_PASSWORD: redis456
      SECRET_KEY: "^U+NyW0(Omty^CEo6q$3DY0RxHaBm@_J*83zEHz(6S_vxGTXOY"
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_CACHE_HOST: redis-cache
    command:
      - sh
      - -c
      - |
        uv pip install netbox-topology-views && /opt/netbox/housekeeping.sh
    volumes:
      - netbox_plugins_config:/etc/netbox/config

    depends_on:
      - netbox

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: J5brHrAXFLQSif0K
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data

  redis:
    image: valkey/valkey:8.0-alpine
    command: [valkey-server, --requirepass, redis123, --appendonly, yes]
    volumes:
      - netbox-redis-data:/data

  redis-cache:
    image: valkey/valkey:8.0-alpine
    command: [valkey-server, --requirepass, redis456]
    volumes:
      - netbox-redis-cache-data:/data

volumes:
  netbox-media-files:
  netbox-reports-files:
  netbox-scripts-files:
  netbox-postgres-data:
  netbox-redis-data:
  netbox-redis-cache-data:
  netbox_plugins_config:
